<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Typing Test System')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/tipyng.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
    <!-- Default theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
    <!-- Semantic UI theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/semantic.min.css"/>
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/bootstrap.min.css"/>
    
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>


        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Typing Test</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/">Início</a>
                </li>
                <li><a class="nav-link" href="/adm/candidate">Candidato</a></li>

                <!-- <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
                </li> -->

                <?php
                    if(isset($_SESSION['user'])){
                        if($_SESSION['user']['nivel']){
                            ?>
                                <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Administrador
                                </a>
                                <ul class=" nav-item dropdown-menu">
                                    <li><a class="dropdown-item" href="/adm/list">Listagem</a></li>
                                </ul>
                                </li>                            
                            <?php
                        }
                    }
                ?>
            </ul>
                <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
                </li> -->
            <?php
                if(isset($_SESSION['user'])){
                    ?>
            <form class="d-flex col-md-2">
                                
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <?= $_SESSION['user']['nome'] ?>
                    </a>
                    <ul class=" nav-item dropdown-menu">
                        <li><a class="dropdown-item" href="/adm/list">Administrativo</a></li>
                        <!-- <li><a class="dropdown-item" href="/adm/candidate">Resultado</a></li> -->
                        <li><a class="dropdown-item" href="/adm/exit">Sair</a></li>
                    </ul>
                    </li>
                </ul>

            </form> 
                    <?php
                } else {
                    ?>
                        <form class="d-flex col-md-2">
                            <div class="navbar-nav">
                                <div class="nav-item text-nowrap">
                                    <a class="nav-link px-3" href="/user/index">Acessar</a>
                                </div>
                            </div>                
                        </form> 
                    
                    <?php
                }
                    ?>
            </div>
        </div>
        </nav>   


        <div class="container">
            <?= $this->content ?>
            <hr>

            <footer class="footer mt-auto py-3 bg-light text-center">
                <div class="container">
                    <span class="text-muted">Idtech -  <?= date('Y') ?> </span>
                </div>
            </footer>

            <!-- <footer class="text-center">
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
                </p>
            </footer> -->
        </div>

        
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js" integrity="sha512-d4KkQohk+HswGs6A1d6Gak6Bb9rMWtxjOa0IiY49Q3TeFd5xAzjWXDCBW9RS7m86FQ4RzM2BdHmdJnnKRYknxw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>


    </body>
</html>
