<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div>
    acesso do candidato

    <form action="/save" method="post">
        <label for="name">Nome</label>
        <input type="text" name="name" id="name" placeholder="Digite o seu nome"/>

        <label for="name">CPF</label>
        <input type="text" name="cpf" id="cpf" placeholder="Digite o seu cpf"/>

        <input type="submit" value="Enviar"/>


    </form>

</div>