<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">

    <?php
        if(isset($msg)){
            ?>
                <div class="alert alert-info"><?= $msg ?></div>
            <?php
        }
    ?>

<?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
