<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>


<div class="container">

<div class="row justify-content-md-center">
    <div class="col col-lg-3">
    </div>
    <div class="col-md-auto col-md-6 jumbotron">
        <h1 class="text-center">Teste de Digitação</h1></br>
        <form action="/tipyng/prepare" method="POST">
            <input type="text" name="cpf" id="cpf" placeholder="Digite o seu CPF" class="form-control" required/>
            
            <?php
                $ano = date('Y');
                $mes = (float) date('m')/3;
                $tri = ceil($mes);
                
                $mesAnt = (int) date('m') > 1 ? (int) (date('m')-1)/3 : (float) date('m')/3 ;
                $triAnt = ceil($mes);

                $processAnterior = "$ano-$triAnt";
                $processAtual = "$ano-$tri";
            ?>

            <div class="form-floating">
            <select class="form-select" id="process" name="process" aria-label="Floating label select process">
                <option value = '<?= $processAtual ?>' selected><?= $processAtual ?></option>
                <option value="2023-1">2023-1</option>
                <option value="2023-2">2023-2</option>
                <option value="2023-3">2023-3</option>
                <option value="2023-4">2023-4</option>

            </select>
            <label for="process">Processo Seletivo</label>
        </div>              
    </br>

    <?php
        if(isset($msg)){
            ?>
                <div class="alert alert-info"><?= $msg ?></div></br>
            <?php
        }
        if(isset($_SESSION['msg'])){
            ?>
                <div class="alert alert-info"><?= $_SESSION['msg'] ?></div></br>
            <?php
        }
    ?>          

            <button class="form-control btn btn-primary" id="btnTipyng">OK</button>
        </form>    
        </div>
    <div class="col col-lg-3">
    </div>
</div>

<div class="row justify-content-md-center">
    <div class="col col-lg-3">
    </div>
    <div class="col-md-auto col-md-6 jumbotron">
        <h1 class="text-center">Resultado</h1></br>
        <form action="/tipyng/prepare" method="POST">
        <input type="text" name="cpf" id="cpf" placeholder="Digite o seu CPF" class="form-control" required/>

        <div class="form-floating">
            <select class="form-select" id="process" name="process" aria-label="Floating label select process">
            <option value = '<?= $processAtual ?>' selected><?= $processAtual ?></option>
                <option value="2023-2">2023-2</option>
                <option value="2023-3">2023-3</option>
                <option value="2023-4">2023-4</option>
            </select>
            <label for="process">Processo Seletivo</label>
        </div>            
        </br>

            <?php
                if(isset($msg)){
                    ?>
                        <div class="alert alert-info"><?= $msg ?></div></br>
                    <?php
                }
                if(isset($_SESSION['msg'])){
                    ?>
                        <div class="alert alert-info"><?= $_SESSION['msg'] ?></div></br>
                    <?php
                }
            ?>          
                          
            <button class="form-control btn btn-primary" id="btnTipyng">OK</button>
        </form>      
    </div>
    <div class="col col-lg-3">
    </div>
</div>

<?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>


<script>

$(document).ready(function(){
    $("#cpf").mask("99999999999");
})

    // $(document).ready(function(){

    //     $("#btnTipyng").click(function(){
    //         const cpf = $("#cpf").val()
    //         alert(cpf)
    //     })

    // })
</script>
