<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Custom\Cript;

?>


<div class="container">

    <?php
 
        if(isset($msg)){
            ?>
                <div class="alert alert-info"><?= $msg ?></div>
            <?php
        }
        if(isset($_SESSION['msg'])){
            ?>
                <div class="alert alert-info"><?= $_SESSION['msg'] ?></div>
            <?php
            unset($_SESSION['msg']);
        }
    ?>

    <div class="row" style="margin-top: 100px;  font-size: 26px">
        <div class="col-sm-6 ">
            <div class="card border-primary"  style="height:300px">
            <div class="card-body">
                <h3 class="card-title">Área do Candidato</h5>
                <p class="card-text">Página com recurso para o candidato como testes e relatórios</p>
            </div>
            <div class="card-footer text-end">
                <a href="/adm/candidate" class="btn btn-primary" rel="noopener noreferrer">Ir</a>
            </div>        
        </div>
        </div>
        <div class="col-sm-6 ">
            <div class="card border-primary"  style="height:300px">
            <div class="card-body">
                <h3 class="card-title">Administrativo</h5>
                <p class="card-text">Área restrita</p>
            </div>
            <div class="card-footer text-end">
                <a href="/user/index" class="btn btn-primary"  rel="noopener noreferrer">Ir</a>
            </div>                    
            </div>
        </div>
        </div>
    </br>

<?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>


<script>

$(document).ready(function(){
    $("#cpf").mask("99999999999");
})

    // $(document).ready(function(){

    //     $("#btnTipyng").click(function(){
    //         const cpf = $("#cpf").val()
    //         alert(cpf)
    //     })

    // })
</script>
