<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Custom\Convert;
use Application\Custom\Cript;
use Application\Custom\VerifySession;

if(isset($msg)){
    ?>
        <div class="alert alert-info"><?= $msg ?></div>
    <?php
    }

// foreach($todos as $t){
//     var_dump($t['candidate']);
// }

?>



<div class="container">
    <br/>
    <h1 class="display-5 text-center">Gerenciador de Candidados</h1>

<!-- Botão para adicionar candidato -->
    <button class="btn  btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalAdd">Candidato</button>

    <!-- Button trigger modal - REMOVE-->
    <div class="modal fade" id="modalAdd" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Candidato</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <div class="modal-body">
               
            <div class="row">
                <div class="col-md-3">
                    <label for="nome">Nome:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="nome" name="nome" placeholder="Digite o número o nome" require/>
                </div>
                <div class="col-md-3">
                    <label for="social">Nome Social:</label>
                    <input type='text' class="form-control" id="social" name="social" placeholder="Digite o seu nome social (Se Houver)" />
                </div>
                <div class="col-md-3">
                    <label for="cpf">CPF:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="cpf" name="cpf" placeholder="Digite o número do seu CPF, para começar" require/>
                </div>
                <div class="col-md-3">
                    <label for="nascimento">Dt. Nasc.:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='date' class="form-control" id="nascimento" name="nascimento" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="cpf">Telefone:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="telefone" name="telefone" placeholder="(xx) 99999-9999" />
                </div>
                <div class="col-md-6">
                    <label for="email">email:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="email" name="email" placeholder="Digite o endereço de e-mail" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="cpf">Cep:</label>
                    <input type='text' class="form-control" id="cep" name="cep" placeholder="(xx) 99999-9999" />
                </div>
                <div class="col-md-6">
                    <label for="email">Endereço:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="endereco" name="endereco" placeholder="Digite o endereço de e-mail" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="cpf">Bairro:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="bairro" name="bairro" placeholder="(xx) 99999-9999" />
                </div>
                <div class="col-md-6">
                    <label for="email">Cidade:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="cidade" name="cidade" placeholder="Digite o endereço de e-mail" />
                </div>
                <div class="col-md-6">
                    <label for="email">Estado:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="estado" name="estado" placeholder="Digite o endereço de e-mail" />
                </div>
            </div>

                <div id="msgAdd"></div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnAddCandidate" data-id="" class="btn btn-primary">Adicionar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
    </div>

    <!-- Botão para inserir frases -->

    <button class="btn btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalFrases">Frases</button>

    <div class="modal fade" id="modalFrases" tabindex="-1" aria-labelledby="modalFrasesLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalFrases">Aviso</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

        <div class="row">
            <div class="col-md-12">
                <label for="frase">Nova Frase:</label>
                <textarea class="form-control" id="frase" name="frase" placeholder="Digite a frase" rows="5"></textarea>
                <p style="color:red">* A frase deverá conter de 500 a 510 caracteres</p>
            </div>
        </div>

        
        <div id="msgFrase"></div>
        </div>
        <div class="modal-footer">
            <button type="button" id="btnAddFrase" class="btn btn-primary">Sim</button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
        </div>
        <div>
            <p class="h5 text-center" style="color:red">São necessários no mínimo 5 frases para o correto funcionamento do teste.</p>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Frases Cadastradas</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>

            <?php
                foreach($frases as $frase){
                    ?>
                    <tr id="fraseRow<?= $frase->getId() ?>">
                        <td> 
                            <textarea name="frase" id="frase<?= $frase->getId() ?>" rows="3" class="form-control" disabled><?= $frase->getPhrase() ?></textarea>
                        </td>
                        <td>
                            </br>
                            <button class="btn btn-sm btn-outline-primary form-control" id="btnDesativarFrase" data-id="<?= $frase->getId() ?>">Remover</button>
                        </td>
                    </tr>     
            <?php               
                }
            ?>

            </tbody>
        </table>        


        </div>
    </div>
    </div>

    <!-- Botão para cadastrar o usuário administrativo -->
    <button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalUsuario">Usuários</button>

    <div class="modal fade" id="modalUsuario" tabindex="-1" aria-labelledby="modalConfigLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalUsuario">Usuário</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">

        <div class="row">
                <div class="col-md-3">
                    <label for="nome">Nome:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="nomeUser" name="nome" placeholder="Digite o número o nome" require/>
                </div>
                <div class="col-md-3">
                    <label for="social">Nome Social:</label>
                    <input type='text' class="form-control" id="socialUser" name="social" placeholder="Digite o seu nome social (Se Houver)" />
                </div>
                <div class="col-md-3">
                    <label for="cpf">CPF:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="cpfUser" name="cpf" placeholder="Digite o número do seu CPF, para começar" require/>
                </div>
                <div class="col-md-3">
                    <label for="nascimento">Dt. Nasc.:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='date' class="form-control" id="nascimentoUser" name="nascimento" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="telefone">Telefone:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="telefoneUser" name="telefone" placeholder="(xx) 99999-9999" />
                </div>
                <div class="col-md-6">
                    <label for="email">email:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="emailUser" name="email" placeholder="Digite o endereço de e-mail" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="cep">Cep:</label>
                    <input type='text' class="form-control" id="cepUser" name="cep" placeholder="(xx) 99999-9999" />
                </div>
                <div class="col-md-6">
                    <label for="endereco">Endereço:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="enderecoUser" name="endereco" placeholder="Digite o endereço de e-mail" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <label for="bairro">Bairro:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="bairroUser" name="bairro" placeholder="(xx) 99999-9999" />
                </div>
                <div class="col-md-6">
                    <label for="cidade">Cidade:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="cidadeUser" name="cidade" placeholder="Digite o endereço de e-mail" />
                </div>
                <div class="col-md-6">
                    <label for="estado">Estado:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='text' class="form-control" id="estadoUser" name="estado" placeholder="Digite o endereço de e-mail" />
                </div>
            </div>

            <div class="row alert alert-info mt-1">
                <div class="col-md-6">
                    <label for="senha1User">Senha:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='password' class="form-control" id="senha1User" name="senha"/>
                </div>
                <div class="col-md-6">
                    <label for="senha2User">Repete a Senha:<span style="color:red;font-weight:bold">*</span></label>
                    <input type='password' class="form-control" id="senha2User" name="senha"/>
                </div>
            </div>            

            <div class="row alert alert-info mt-1">
                <div class="col-md-12">
                <label for="nivelUser">Nível de Acesso</label>
                <select class="form-select" id="nivelUser" aria-label="Default select example">
                    <option selected>Selecione</option>
                    <option value="1">Comum</option>
                    <option value="2">Gerencial</option>
                    <option value="3">Suporte</option>
                </select>                    
                </div>
            </div>                   

        <div id="msgFrase"></div>
        </div>
            <div class="modal-footer">
                <button type="button" id="btnAddUsuario" class="btn btn-primary">Sim</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
            </div>

            <div class="m-2">
                <table class="table table-responsible">
                    <thead>
                        <tr>
                            <th>Nome/Social</th>
                            <th>CPF</th>
                            <th>Nascimento</th>
                            <th>Telefone</th>
                            <th>Email</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                            foreach($users as $usuario){
                                ?>
                                    <tr id="userRow<?php echo $usuario->getId(); ?>">
                                        <td><?= !empty($usuario->getSocial()) ? $usuario->getSocial() : $usuario->getNome(); ?></td>
                                        <td><?php echo $usuario->getCpf(); ?></td>
                                        <td></td>
                                        <td><?php echo $usuario->getTelefone(); ?></td>
                                        <td><?php echo $usuario->getEmail(); ?></td>
                                        <td><button id="btnDesativarUsuario" class="btn btn-alert btn-sm btn-outline-primary form-control" data-id="<?php echo $usuario->getId(); ?>">Desativar</button></td>
                                    </tr>
                                <?php
                            }
                        ?>
                </tbody>
                </table>
            
        </div>

        </div>
    </div>
    </div>

    
    <!-- <div class="btn-toolbar mb-2 mb-md-0 float-right">
        <div class="btn-group me-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Usuário</button>
        </div>
    </div> -->

<ul class="list-group mt-2">
    <li class="list-group-item active text-center"><h2>Listagem de Candidatos</h2></li>
</ul>
<table class="table table-striped table-hover">
    <thead class="table-primary">
        <tr>
            <th scope='col'>#</th>
            <th scope='col'>Processo</th>
            <th scope='col'>Nome/Social</th>
            <th scope='col'>CPF</th>
            <th scope='col'>Dt.: Nasc.</th>
            <th scope='col'>Fone</th>
            <th scope='col'>E-mail</th>
            <th scope='col'>TPM</th>
            <th scope='col'>Precisão</th>
            <th scope='col'>Tempo</th>
            <th scope='col' class="text-center">Ações</th>
        </tr>
    </thead>
    
 <?php
    foreach($candidates as $candidate){
        ?>

        <tr>
            <!-- <th scope='col'>#</th> -->     
            <td><?= $candidate['id'] ?></td>
            <!-- <th scope='col'>Process</th> -->     
            <td><?= $candidate['process'] ?></td>
            <!-- <th scope='col'>Nome/Social</th> -->     
            <td><?= $candidate['nome'] ?></br><strong style="color:red"> <?= $candidate['cancel'] ? $candidate['justify'] : '' ?></strong</td>
            <!-- <th scope='col'>CPF</th> -->
            <td><?= $candidate['cpf']?></td>
            <td>
                <?= Convert::dateBrl($candidate['nascimento']); ?>
            </td>
            <td><?=$candidate['telefone'] ?></td>
            <td><?=$candidate['email']?></td>
            <td><?=$candidate['tpm']?></td>
            <td><?=$candidate['precisao']?></td>
            <td><?=$candidate['seconds']?></td>

            <td scope='col'>
                <!-- Botão de remover o candidato -->
                <button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#modalCancel<?= $candidate['id'] ?>">Cancelar</button>

                <div class="modal fade" id="modalCancel<?= $candidate['id'] ?>" tabindex="-1" aria-labelledby="modalCancel<?= $candidate['id'] ?>Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="modalCancel<?= $candidate['id'] ?>">Aviso</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">

                    <div class="row">
                        <div class="col-md-12">
                            <label for="Justificativa">Nome:</label>
                            <textarea class="form-control" id="justificativaCancel<?= $candidate['id'] ?>" name="JustificativaCancel" placeholder="Digite a justificativa do cancelamento do teste de digitação"></textarea>
                        </div>
                    </div>

                    <div id="msgCancel<?= $candidate['id'] ?>"></div>
                    
                </div>
                    <div class="modal-footer">
                        <button type="button" id="btnCancelCandidato" data-id="<?= $candidate['id'] ?>" data-test="<?= $candidate['typing'] ?>" class="btn btn-primary">Sim</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
                    </div>
                    </div>
                </div>
                </div>
                <!-- Botão ver os dados do candidato -->
                <button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#modal<?= $candidate['id'] ?>">Ver</button>

                <div class="modal fade" id="modal<?= $candidate['id'] ?>" tabindex="-1" aria-labelledby="modal<?= $candidate['id'] ?>Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                    <div class="modal-header text-center">
                        <h1 class="modal-title fs-5 text-center" id="modal<?= $candidate['id'] ?>Label">Teste de Digitação - Processo Seletivo <?= $candidate['process'] ?> </h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                    <div class="row">
                        <div class="col-md-3">
                            <label for="nome">Nome:</label>
                            <input type='text' class="form-control" id="nomeView<?= $candidate['id'] ?>" name="nome" placeholder="Digite o número o nome" value="<?= $candidate['nome'] ?>" disabled/>
                        </div>
                        <div class="col-md-3">
                            <label for="social">Nome Social:</label>
                            <input type='text' class="form-control" id="socialView<?= $candidate['id'] ?>" name="social" placeholder="Digite o seu nome social (Se Houver)" value="<?= $candidate['social'] ?>" disabled/>
                        </div>
                        <div class="col-md-3">
                            <label for="cpf">CPF:</label>
                            <input type='text' class="form-control" id="cpfView<?= $candidate['id'] ?>" name="cpf" placeholder="Digite o número do seu CPF, para começar" value="<?= $candidate['cpf'] ?>" disabled/>
                        </div>
                        <div class="col-md-3">
                            <label for="nascimento">Dt. Nasc.:</label>
                            <input type='date' class="form-control" id="nascimentoView<?= $candidate['id'] ?>" name="nascimento" value="<?= Convert::dateUsa($candidate['nascimento'])?>" disabled/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="cpf">Telefone:</label>
                            <input type='text' class="form-control" id="telefoneView<?= $candidate['id'] ?>" name="telefone" placeholder="(xx) 99999-9999" value="<?= $candidate['telefone'] ?>" disabled/>
                        </div>
                        <div class="col-md-6">
                            <label for="email">email:</label>
                            <input type='text' class="form-control" id="emailView<?= $candidate['id'] ?>" name="email" placeholder="Digite o endereço de e-mail" value="<?= $candidate['email'] ?>" disabled/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="cpf">Cep:</label>
                            <input type='text' class="form-control" id="cepView<?= $candidate['id'] ?>" name="cep" placeholder="(xx) 99999-9999" value="<?= $candidate['cep'] ?>" disabled/>
                        </div>
                        <div class="col-md-6">
                            <label for="email">Endereço:</label>
                            <input type='text' class="form-control" id="enderecoView<?= $candidate['id'] ?>" name="endereco" placeholder="Digite o endereço de e-mail" value="<?= $candidate['endereco'] ?>" disabled/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="cpf">Bairro:</label>
                            <input type='text' class="form-control" id="bairroView<?= $candidate['id'] ?>" name="bairro" placeholder="(xx) 99999-9999" value="<?= $candidate['bairro'] ?>" disabled/>
                        </div>
                        <div class="col-md-6">
                            <label for="email">Cidade:</label>
                            <input type='text' class="form-control" id="cidadeView<?= $candidate['id'] ?>" name="cidade" placeholder="Digite o endereço de e-mail" value="<?= $candidate['cidade'] ?>" disabled/>
                        </div>
                        <div class="col-md-6">
                            <label for="email">Estado:</label>
                            <input type='text' class="form-control" id="estadoView<?= $candidate['id'] ?>" name="estado" placeholder="Digite o endereço de e-mail" value="<?= $candidate['estado'] ?>" disabled/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
    </br>
                            <p class="display-6 text-center">Resultado</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="cpf">Processo:</label>
                            <input type='text' class="form-control" id="bairroView<?= $candidate['id'] ?>" name="bairro" placeholder="CPF" value="<?= $candidate['process'] ?>" disabled/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <label for="email">Início:</label>
                            <input type='text' class="form-control" id="estadoView<?= $candidate['id'] ?>" name="estado" placeholder="Início" value="<?= Convert::dateBrlFull($candidate['inicio']) ?>" disabled/>
                        </div>
                        <div class="col-md-5">
                            <label for="email">Término:</label>
                            <input type='text' class="form-control" id="estadoView<?= $candidate['id'] ?>" name="estado" placeholder="Término" value="<?= Convert::dateBrlFull($candidate['termino']) ?>" disabled/>
                        </div>
                        <div class="col-md-2">
                            <label for="email">Duração:</label>
                            <input type='text' class="form-control" id="estadoView<?= $candidate['id'] ?>" name="estado" placeholder="segundos" value="<?= $candidate['seconds'] ?> s" disabled/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="email">Caracteres:</label>
                            <input type='text' class="form-control" id="estadoView<?= $candidate['id'] ?>" name="estado" placeholder="caracteres" value="<?= $candidate['characters'] ?>" disabled/>
                        </div>
                        <div class="col-md-4">
                            <label for="email">Erros:</label>
                            <input type='text' class="form-control" id="estadoView<?= $candidate['id'] ?>" name="estado" placeholder="erros" value="<?= $candidate['errors'] ?>" disabled/>
                        </div>
                        <div class="col-md-4">
                            <label for="email">Acertos:</label>
                            <input type='text' class="form-control" id="estadoView<?= $candidate['id'] ?>" name="estado" placeholder="acertos" value="<?= $candidate['hits'] ?>" disabled/>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="email">Precisão:</label>
                            <input type='text' class="form-control" id="estadoView<?= $candidate['id'] ?>" name="estado" placeholder="precisão" value="<?= $candidate['precisao'] ?> %" disabled/>
                        </div>
                        <div class="col-md-6">
                            <label for="email">TPM:</label>
                            <input type='text' class="form-control" id="estadoView<?= $candidate['id'] ?>" name="estado" placeholder="TPM" value="<?= $candidate['tpm'] ?>" disabled/>
                        </div>
                    </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Sair</button>
                    </div>
                    </div>
                </div>
                </div>
    </div>
                <!-- Botão de remover o candidato -->
                <button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#modalRemove<?= $candidate['id'] ?>">Remover</button>

                <div class="modal fade" id="modalRemove<?= $candidate['id'] ?>" tabindex="-1" aria-labelledby="modalRemove<?= $candidate['id'] ?>Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="modalRemove<?= $candidate['id'] ?>">Aviso</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Você confirma a exclusão do candidato <?= $candidate['nome'] ?>? 
                        <div id="msgDelete<?= $candidate['id'] ?>"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" id="btnRemoverCandidato" data-id="<?= $candidate['id'] ?>" class="btn btn-primary">Sim</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
                    </div>
                    </div>
                </div>
                </div>

            <!-- Botão para atualizar os dados do candidato-->
            <button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#modalUpdate<?= $candidate['id'] ?>">Atualizar</button></li>

            <!-- Modal -->
            <div class="modal fade" id="modalUpdate<?= $candidate['id'] ?>" tabindex="-1" aria-labelledby="modalUpdate<?= $candidate['id'] ?>Label" aria-hidden="true">
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modalUpdate<?= $candidate['id'] ?>Label">Edição do Candidato <?= $candidate['nome'] ?><?= $candidate['id'] ?></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <div class="row">
                        <div class="col-md-3">
                            <label for="nome">Nome:<span style="color:red;font-weight:bold">*</span></label>
                            <input type='text' class="form-control" id="nomeUpdate<?= $candidate['id'] ?>" name="nome" placeholder="Digite o número o nome" value="<?= $candidate['nome'] ?>"/>
                        </div>
                        <div class="col-md-3">
                            <label for="social">Nome Social:</label>
                            <input type='text' class="form-control" id="socialUpdate<?= $candidate['id'] ?>" name="social" placeholder="Digite o seu nome social (Se Houver)" value="<?= $candidate['social'] ?>"/>
                        </div>
                        <div class="col-md-3">
                            <label for="cpf">CPF:<span style="color:red;font-weight:bold">*</span></label>
                            <input type='text' class="form-control" id="cpfUpdate<?= $candidate['id'] ?>" name="cpf" placeholder="Digite o número do seu CPF, para começar" value="<?= $candidate['cpf'] ?>"/>
                        </div>
                        <div class="col-md-3">
                            <label for="nascimento">Dt. Nasc.:<span style="color:red;font-weight:bold">*</span></label>
                            <input type='date' class="form-control" id="nascimentoUpdate<?= $candidate['id'] ?>" name="nascimento" value="<?= Convert::dateUsa($candidate['nascimento'])?>"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="cpf">Telefone:<span style="color:red;font-weight:bold">*</span></label>
                            <input type='text' class="form-control" id="telefoneUpdate<?= $candidate['id'] ?>" name="telefone" placeholder="(xx) 99999-9999" value="<?= $candidate['telefone'] ?>"/>
                        </div>
                        <div class="col-md-6">
                            <label for="email">email:<span style="color:red;font-weight:bold">*</span></label>
                            <input type='text' class="form-control" id="emailUpdate<?= $candidate['id'] ?>" name="email" placeholder="Digite o endereço de e-mail" value="<?= $candidate['email'] ?>"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="cpf">Cep:</label>
                            <input type='text' class="form-control" id="cepUpdate<?= $candidate['id'] ?>" name="cep" placeholder="74000000" value="<?= $candidate['cep'] ?>"/>
                        </div>
                        <div class="col-md-6">
                            <label for="email">Endereço:<span style="color:red;font-weight:bold">*</span></label>
                            <input type='text' class="form-control" id="enderecoUpdate<?= $candidate['id'] ?>" name="endereco" placeholder="Digite o seu endereço" value="<?= $candidate['endereco'] ?>"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="cpf">Bairro:<span style="color:red;font-weight:bold">*</span></label>
                            <input type='text' class="form-control" id="bairroUpdate<?= $candidate['id'] ?>" name="bairro" placeholder="Bairro" value="<?= $candidate['bairro'] ?>"/>
                        </div>
                        <div class="col-md-6">
                            <label for="email">Cidade:<span style="color:red;font-weight:bold">*</span></label>
                            <input type='text' class="form-control" id="cidadeUpdate<?= $candidate['id'] ?>" name="cidade" placeholder="Cidade" value="<?= $candidate['cidade'] ?>"/>
                        </div>
                        <div class="col-md-6">
                            <label for="email">Estado:<span style="color:red;font-weight:bold">*</span></label>
                            <input type='text' class="form-control" id="estadoUpdate<?= $candidate['id'] ?>" name="estado" placeholder="Estado" value="<?= $candidate['estado'] ?>"/>
                        </div>
                    </div>
                    <div id="msgUpdate<?= $candidate['id'] ?>"></div>

                </div>
                <div class="modal-footer"> 
                    <button type="button" id="btnUpdateCandidate" data-id="<?= $candidate['id'] ?>" class="btn btn-primary">Salvar</button>                   
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>

                </div>

                </div>
            </div>
            </div>

            </td>
        </tr>

        <?php
    }
    ?>

</table>

</div>


    <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>

    <script>
// Chamada Ajax para página de teste
// $(document).on("blur", "#cpf", function(){
//     const cpf = $(this).val();
//     $.ajax({ 
//         type : 'POST',
//         url : '/test',
//         data : {cpf},
//         dataType: 'html',
//         success: function(data){  
//             alert(data);
//                  //success function
//                  //current date is in data.currentdate
//         },
//         error: function(jqXHR,textStatus,errorThrown){
//                  var error = $.parseJSON(jqXHR.responseText);
//                  var content = error.content;
//                  console.log(content.message);
//                  if(content.display_exceptions)
//                  console.log(content.exception.xdebug_message);
//         },
    
//     }) ;

// })

function updatePage(){
    window.location.replace("/adm/list");
}

$(document).ready(function(){
    $("input[name=cpf]").mask("99999999999");
    $("input[name=telefone]").mask("(99) 99999-9999");
    $("input[name=cep]").mask("99999999");
})



$(document).on('click','#btnRemoverCandidato',function(){
    const id = $(this).data('id')

        $.ajax({ 
            type : 'POST',
            url : '/adm/delete',
            data : {id},
            dataType: 'html',
            success: function(data){  
                alertify.alert('Aviso', `${data}`);
                updatePage()                
                // $('#msgDelete'+id).html(`<div class="alert alert-info alert-dismissible" role="alert">${data}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`)
            },
            error: function(jqXHR,textStatus,errorThrown){
                var error = $.parseJSON(jqXHR.responseText);
                var content = error.content;
                console.log(content.message);
                if(content.display_exceptions)
                console.log(content.exception.xdebug_message);
            },
        
        }) ;    

})
$(document).on('click','#btnCancelCandidato',function(){
    const id = $(this).data('id')
    const justify = $('#justificativaCancel'+id).val()
    const test = $(this).data('test')
    
    if(id && test){
        $.ajax({ 
            type : 'POST',
            url : '/tipyng/cancel',
            data : {test, justify},
            dataType: 'html',
            success: function(data){  
                alertify.alert('Aviso', `${data}`);
                // $('#msgDelete'+id).html(`<div class="alert alert-info alert-dismissible" role="alert">${data}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`)
            },
            error: function(jqXHR,textStatus,errorThrown){
                var error = $.parseJSON(jqXHR.responseText);
                var content = error.content;
                console.log(content.message);
                if(content.display_exceptions)
                console.log(content.exception.xdebug_message);
            },
        
        }) ;    
    } else {
        alertify.alert('Aviso', `Campo de preenchimento obrigatório!`);
    }
})

$("#btnAddCandidate").click(function(){
    const id = $(this).data('id');
    const nome = $("#nome").val();
    const social = $("#social").val();
    const cpf = $("#cpf").val();
    const nascimento = $("#nascimento").val();
    const telefone = $("#telefone").val();
    const email = $("#email").val();
    const cep = $("#cep").val();
    const endereco = $("#endereco").val();
    const bairro = $("#bairro").val();
    const cidade = $("#cidade").val();
    const estado = $("#estado").val();
    // name social cpf nascimento telefone email
    // console.log(id, name, cpf)
    if(cpf && nascimento && telefone && email && (nome || social)){

        $.ajax({ 
            type : 'POST',
            url : '/adm/saveOrUpdate',
            data : {id, nome, social, cpf, nascimento, telefone, email, cep, endereco, bairro, cidade, estado},
            dataType: 'html',
            success: function(data){  
                alertify.alert('Aviso', `${data}`);
                // $('#msgAdd'+id).html(`<div class="alert alert-info alert-dismissible" role="alert">${data}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`)
            },
            error: function(jqXHR,textStatus,errorThrown){
                var error = $.parseJSON(jqXHR.responseText);
                var content = error.content;
                console.log(content.message);
                if(content.display_exceptions)
                console.log(content.exception.xdebug_message);
            },
        }) ;
    } else {
        alertify.alert('Aviso', 'Campos de preenchimento obrigatório (*)');
        // alertify.alert('Aviso', 'Campos de preenchimento obrigatório (*)', function(){ alertify.success('Ok'); });
        // alert('Campos de preenchimento obrigatório (*)')
    }

})
$("#btnAddUsuario").click(function(){
    const id = $(this).data('id');
    const nome = $("#nomeUser").val();
    const social = $("#socialUser").val();
    const cpf = $("#cpfUser").val();
    const nascimento = $("#nascimentoUser").val();
    const telefone = $("#telefoneUser").val();
    const email = $("#emailUser").val();
    const cep = $("#cepUser").val();
    const endereco = $("#enderecoUser").val();
    const bairro = $("#bairroUser").val();
    const cidade = $("#cidadeUser").val();
    const estado = $("#estadoUser").val();
    const nivel = $("#nivelUser").val();
    const senha1 = $("#senha1User").val();
    const senha2 = $("#senha2User").val();
    // name social cpf nascimento telefone email
    // console.log(id, name, cpf)
    if(cpf && nascimento && telefone && email && senha1 && senha2 && nivel &&(nome || social)){
        if(senha1 === senha2){
            if(senha1.length > 7){
                $.ajax({ 
                    type : 'POST',
                    url : '/user/saveOrUpdate',
                    data : {id, nome, social, cpf, nascimento, telefone, email, cep, endereco, bairro, cidade, estado, nivel, senha1},
                    dataType: 'html',
                    success: function(data){  
                        alertify.alert('Aviso', `${data}`);
                        // $('#msgAdd'+id).html(`<div class="alert alert-info alert-dismissible" role="alert">${data}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`)
                    },
                    error: function(jqXHR,textStatus,errorThrown){
                        var error = $.parseJSON(jqXHR.responseText);
                        var content = error.content;
                        console.log(content.message);
                        if(content.display_exceptions)
                        console.log(content.exception.xdebug_message);
                    },
                }) ;
            } else {
                alertify.alert('Aviso', 'As senhas devem ter no mínimo 8 caracteres');            
            }
        } else {
            alertify.alert('Aviso', 'As senhas são diferentes');            
        }

    } else {
        alertify.alert('Aviso', 'Campos de preenchimento obrigatório (*)');
        // alertify.alert('Aviso', 'Campos de preenchimento obrigatório (*)', function(){ alertify.success('Ok'); });
        // alert('Campos de preenchimento obrigatório (*)')
    }

})

$("#btnAddFrase").click(function(){
    const id = '';
    const frase = $("#frase").val();
    // name social cpf nascimento telefone email
    // console.log(id, name, cpf)
    if(frase){
        // 350 até 370 caracteres
        if(frase.length > 499 && frase.length < 511){

            // if(frase.includes('–')){
            //     frase = frase.replace('–', '-')
            // }

            $.ajax({ 
                type : 'POST',
                url : '/phrase/saveorupdate',
                data : {id, frase},
                dataType: 'html',
                success: function(data){  
                    alertify.alert('Aviso', `${data}`);
                    // $('#msgAdd'+id).html(`<div class="alert alert-info alert-dismissible" role="alert">${data}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`)
                },
                error: function(jqXHR,textStatus,errorThrown){
                    var error = $.parseJSON(jqXHR.responseText);
                    var content = error.content;
                    console.log(content.message);
                    if(content.display_exceptions)
                    console.log(content.exception.xdebug_message);
                },
            }) ;
        } else {
            alertify.alert(`A frase para o teste tem que ter o comprimento mínimo de 500 e no máximo de 510 caracteres. A frase atual tem ${frase.length}`);
        }
    } else {
        alertify.alert('Aviso', 'Campos de preenchimento obrigatório (*)');
        // alertify.alert('Aviso', 'Campos de preenchimento obrigatório (*)', function(){ alertify.success('Ok'); });
        // alert('Campos de preenchimento obrigatório (*)')
    }

})

$(document).on('click','#btnDesativarFrase', function(){
    const id = $(this).data('id');
    const frase = $("#frase"+id).val();

    // console.log(id, frase)
    if(id && frase){
        $.ajax({ 
        type : 'POST',
        url : '/phrase/remove',
        data : {id, frase},
        dataType: 'html',
        success: function(data){  
            $("#fraseRow"+id).hide()
            alertify.alert('Aviso', `${data}`);

            // $('#msgAdd'+id).html(`<div class="alert alert-info alert-dismissible" role="alert">${data}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`)
        },
        error: function(jqXHR,textStatus,errorThrown){
            var error = $.parseJSON(jqXHR.responseText);
            var content = error.content;
            console.log(content.message);
            if(content.display_exceptions)
            console.log(content.exception.xdebug_message);
        },
    }) ;
  }

})

$(document).on("click", "#btnUpdateCandidate",function(){
    const id = $(this).data('id');

    const nome = $("#nomeUpdate"+id).val();
    const social = $("#socialUpdate"+id).val();
    const cpf = $("#cpfUpdate"+id).val();
    const nascimento = $("#nascimentoUpdate"+id).val();
    
    const telefone = $("#telefoneUpdate"+id).val();
    const email = $("#emailUpdate"+id).val();
    
    const cep = $("#cepUpdate"+id).val();
    const endereco = $("#enderecoUpdate"+id).val();
    const bairro = $("#bairroUpdate"+id).val();
    const cidade = $("#cidadeUpdate"+id).val();
    const estado = $("#estadoUpdate"+id).val();

    if(id && cpf && nascimento && telefone && email && (nome || social)){

        $.ajax({ 
        type : 'POST',
        url : '/adm/saveOrUpdate',
        data : {id, nome, social, cpf, nascimento, telefone, email, cep, endereco, bairro, cidade, estado},
        dataType: 'html',
        success: function(data){  
            alertify.alert('Aviso', `${data}`);
            // $('#msgUpdate'+id).html(`<div class="alert alert-info alert-dismissible" role="alert">${data}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`)
        },
        error: function(jqXHR,textStatus,errorThrown){
            var error = $.parseJSON(jqXHR.responseText);
            var content = error.content;
            console.log(content.message);
            if(content.display_exceptions)
            console.log(content.exception.xdebug_message);
        },
    
    });
} else {
    alertify.alert('Aviso', 'Campos de preenchimento obrigatório (*)');
}

})



$(document).on("click", "#btnCancelCandidato",function(){
    const id = $(this).data('id');

    const justificativa = $("#justificativaCancel"+id).val();

    if(id && justificativa){

        $.ajax({ 
        type : 'POST',
        url : '/adm/cancelTest',
        data : {id, justificativa},
        dataType: 'html',
        success: function(data){  
            alertify.alert('Aviso', `${data}`);
            // $('#msgUpdate'+id).html(`<div class="alert alert-info alert-dismissible" role="alert">${data}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`)
        },
        error: function(jqXHR,textStatus,errorThrown){
            var error = $.parseJSON(jqXHR.responseText);
            var content = error.content;
            console.log(content.message);
            if(content.display_exceptions)
            console.log(content.exception.xdebug_message);
        },
    
    });
} else {
    alertify.alert('Aviso', 'Campos de preenchimento obrigatório (*)');
}

})

$(document).on('click','#btnDesativarUsuario', function(){
    const id = $(this).data('id');

    // console.log(id, frase)
    if(id){
        $.ajax({ 
        type : 'POST',
        url : '/user/remove',
        data : {id},
        dataType: 'html',
        success: function(data){  
            $("#userRow"+id).hide()
            alertify.alert('Aviso', `${data}`);

            // $('#msgAdd'+id).html(`<div class="alert alert-info alert-dismissible" role="alert">${data}<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div>`)
        },
        error: function(jqXHR,textStatus,errorThrown){
            var error = $.parseJSON(jqXHR.responseText);
            var content = error.content;
            console.log(content.message);
            if(content.display_exceptions)
            console.log(content.exception.xdebug_message);
        },
    }) ;
  }

})


// Gerar janela Modal
// $("#btn-mensagem").click(function(){
//     $("#modal-mensagem").modal();
// });



    // $.ajax({ 
    //     type : 'POST',
    //     url : '/administratif/personnel/getcurrenttime',
    //     data : {value: changedValue},
    //     dataType: 'json',
    //     success: function(data){  
    //              //success function
    //              //current date is in data.currentdate
    //     },
    //     error: function(jqXHR,textStatus,errorThrown){
    //              var error = $.parseJSON(jqXHR.responseText);
    //              var content = error.content;
    //              console.log(content.message);
    //              if(content.display_exceptions)
    //              console.log(content.exception.xdebug_message);
    //     },
    
    // }) ;
    </script>
