<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome candidate for typing</h1>

    <?php
        if(isset($msg)) {
            ?>
                <div class="alert alert-info"><?= $msg ?></div>
            <?php
        }
    ?>

    <form action="/save" method="POST">
        <div class="row">
            <div class="col-md-6">
                <input type='text' class="form-control" name="cpf" placeholder="Digite o número do seu CPF, para começar"/>
                <input type='text' class="form-control" name="nome" placeholder="Digite o número o nome"/>
            </div>
            <div class="col-md-6">
                <input type="submit" value="enviar"  class="form-control">
            </div>
        </div>
    </form>
</div>
